# Generated by Django 5.2 on 2025-04-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='audio',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.ImageField(default=1, upload_to='exercises/images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='question_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
