# Generated by Django 5.2 on 2025-04-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_remove_exercise_audio_alter_exercise_correct_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='user',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='correct_answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.ImageField(upload_to='exercises/'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='question_text',
            field=models.CharField(max_length=255),
        ),
    ]
