# Generated by Django 5.2 on 2025-04-23 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_remove_exercise_user_alter_exercise_correct_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='image',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='question_text',
        ),
    ]
